Record definition of enums
maglnet/ComposerRequireChecker pull request #320
Opened 2021-11-14 20:49 UTC by iggyvolz

Records definition of enums so they are no longer shown as unknown symbols.  Probably needs some more work in https://github.com/maglnet/ComposerRequireChecker/blob/3.6.x/src/ComposerRequireChecker/NodeVisitor/UsedSymbolCollector.php so that it can record symbols used by enums - but this is a start.

2021-11-15 08:45 UTC, Ocramius requested changes
Heyo, overall looks simple/sweet, but:

 * we need tests for these additions
 * the minimum `nikic/php-parser` dependency version needs to be bumped

2021-11-15 14:41 UTC, iggyvolz commented
> Heyo, overall looks simple/sweet, but:
> 
>     * we need tests for these additions
> 
>     * the minimum `nikic/php-parser` dependency version needs to be bumped

Will do - not sure if I'll have time to get to this later this week but definitely by next week.

2021-12-03 16:01 UTC, dkreuer commented
Hey @iggyvolz are you still working on this PR? Or may I jump in and help you out?

2021-12-04 18:08 UTC, iggyvolz commented
> Hey @iggyvolz are you still working on this PR? Or may I jump in and help you out?

@dkreuer this totally fell off my radar - if you want to jump in feel free

2021-12-04 18:25 UTC, dkreuer commented
In that case I‘d provide a new PR from main branch since it looks like the dependency update has already been done there (and I don’t know how I could contribute to your fork 😳).

2021-12-06 08:23 UTC, dkreuer commented
Superseeded by #329 (which is merged and released).

2021-12-06 08:31 UTC, closed without merging