#354 Make sure language types are always in the symbol whitelist
maglnet/ComposerRequireChecker pull request #355
Opened 2022-08-29 11:26 UTC by willemstuursma

2022-08-29 11:29 UTC, Ocramius approved these changes
LGTM 👍

2022-08-29 11:31 UTC, Ocramius commented
Some CS changes needed

2022-08-29 11:34 UTC, willemstuursma commented
> Some CS changes needed

Yes, I will take care of it.

2022-08-29 11:38 UTC, DanielBadura commented
Should we also remove the whitelist part on the default config json to prevent confusion on this topic?

2022-08-29 11:39 UTC, Ocramius commented
Can certainly be done 👍

2022-08-30 07:26 UTC, willemstuursma commented
@DanielBadura @Ocramius Please let me know if this is satisfactory or feel free to merge.

2022-08-30 07:56 UTC, DanielBadura approved these changes

2022-08-30 08:00 UTC, Ocramius requested changes
There is one mutant to be fixed, indicating a missing test:

```diff
2) /home/runner/work/ComposerRequireChecker/ComposerRequireChecker/src/ComposerRequireChecker/Cli/Options.php:108    [M] UnwrapArrayUnique

--- Original
+++ New
@@ @@
          * Make sure the language types (e.g. 'true', 'false', 'object', 'mixed') are always included in the symbol
          * whitelist. If these are omitted the results can be pretty unexpected.
          */
-        $this->symbolWhitelist = array_unique(array_merge(self::PHP_LANGUAGE_TYPES, $symbolWhitelist));
+        $this->symbolWhitelist = array_merge(self::PHP_LANGUAGE_TYPES, $symbolWhitelist);
     }
     /**
      * @param array<string> $phpCoreExtensions
```

See https://github.com/maglnet/ComposerRequireChecker/runs/8087054988?check_suite_focus=true#step:9:74

2022-08-30 09:18 UTC, willemstuursma commented
Cheers, I added an assertion that should fix it

2022-08-30 09:36 UTC, merged

2022-08-30 09:36 UTC, Ocramius commented
Thanks @willemstuursma!