Allow specifying a relative file via phar, assert that the requested file exists
maglnet/ComposerRequireChecker pull request #511
Opened 2024-02-13 16:58 UTC by fredden

There are two main changes in this pull request:
1. Relative paths now work both via Composer installation and when using the phar file. This fixes #140.
1. The file provided by the `--config-file` argument must exist. Previously when the argument was the same as the default, then missing files would be silently ignored. This fixes #507.

2024-02-13 17:00 UTC, Ocramius requested changes
OK with the change, but to prevent regressions, I'd expect automated tests to be in place? :thinking:

2024-02-13 18:34 UTC, fredden commented
I've added a couple of tests to cover the "default argument value" part of this change. The other changes are only visible with the phar. What's the best way to add tests for that?

2024-02-13 18:37 UTC, Ocramius commented
> The other changes are only visible with the phar.

That's because the relative path is broken, right? Any way we can convince the suite of a changed CWD? :thinking:

2024-02-15 07:38 UTC, fredden commented
I've opened #515 to get some test coverage of the phar file. When that lands, I'll update this pull request to include a check for the phar bug we're fixing here.

2024-03-05 11:47 UTC, Ocramius commented
@fredden I see this being regularly rebased, but staying red: what are you planning for it, specifically? 🤔

2024-03-05 16:18 UTC, fredden commented
I get notifications when there are merge conflicts, which I then resolve. After #512 has landed, I expect the tests here to pass. As far as I know, the changes here are good, but the test suite is currently incompatible, which is why #512 is open.

(For #512, I am currently spinning up a Windows virtual machine so I can resolve the test failures over there.)

2024-03-05 16:51 UTC, Ocramius commented
But then I see #512 also red? :D

2024-03-05 17:07 UTC, fredden commented
> But then I see https://github.com/maglnet/ComposerRequireChecker/pull/512 also red

For now, yes. As mentioned, I'm working on getting a copy of Windows so I can make that green.

2024-03-05 17:29 UTC, Ocramius commented
Thanks, that's the context I was missing! :muscle:

2024-03-08 14:32 UTC, Ocramius approved these changes
Thanks @fredden!

2024-03-08 14:33 UTC, merged